runtime: python27
api_version: 1
threadsafe: true
handlers:
  - url: /(.*\.(gif|png|jpg|css|js|json|woff2|ico)(|\.map))$
    static_files: dist/SimFrontEnd/\1
    upload: dist/(.*)(|\.map)
  - url: /(.*)
    static_files: dist/SimFrontEnd/index.html
    upload: dist/SimFrontEnd/index.html
skip_files:
  - e2e/
  - node_modules/
  - src/
  - coverage
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE